version: '3'

services:
  gateway:
    build: 
      context: ../
      dockerfile: ./docker/gateway/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - "rabbitmq"
    command: ["node", "main.js"]
  hero:
    build: 
      context: ../
      dockerfile: ./docker/hero/Dockerfile
    depends_on:
      - "rabbitmq"
    command: ["node", "main.js"]
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672:5672
